import type { Dispatch, SetStateAction } from "react";
import type { Item, ItemCategory } from "../../../api/itemsApi";
import type { Sale, SalePayload } from "../../../api/salesApi";
import type { Customer } from "../../../api/customersApi";
import type { OfferPreviewResult } from "../../../api/offersApi";
import type { SaleOfferEngineState } from "./useSaleOfferEngine";
import type { SalesPosApplicableOffer } from "../../../api/salesApi";
import type { SaleLineDraft } from "./SaleLineItemsSection";
import type { PosPaymentMethod } from "./posSaleConstants";
import type { PosCategoryTab } from "./posSaleCatalogFilter";
import type { PosSubCategoryTab } from "./PosSubCategoryTabs";
import type { PosSalesPriceMode } from "./posSalePricing";
import type { ChequePaymentDetails } from "./PosChequeBankDialog";

export type PosSaleView = "products" | "checkout";

export interface PosSaleSession {
  view: PosSaleView;
  setView: Dispatch<SetStateAction<PosSaleView>>;
  form: SalePayload;
  setForm: Dispatch<SetStateAction<SalePayload>>;
  lines: SaleLineDraft[];
  setLines: Dispatch<SetStateAction<SaleLineDraft[]>>;
  categoryTab: PosCategoryTab;
  subCategoryTab: PosSubCategoryTab;
  catalogSearch: string;
  setCatalogSearch: Dispatch<SetStateAction<string>>;
  paymentMethod: PosPaymentMethod;
  amountReceived: number;
  setAmountReceived: Dispatch<SetStateAction<number>>;
  chequeDetails: ChequePaymentDetails | null;
  setChequeDialogOpen: Dispatch<SetStateAction<boolean>>;
  offerDiscount: number;
  setOfferDiscount: Dispatch<SetStateAction<number>>;
  offerPreview: OfferPreviewResult | null;
  setOfferPreview: Dispatch<SetStateAction<OfferPreviewResult | null>>;
  offerUpdating: boolean;
  offerEngine: SaleOfferEngineState;
  selectedOffer: SalesPosApplicableOffer | null;
  activeHoldSaleId: number | null;
  holdPin: string;
  setHoldPin: Dispatch<SetStateAction<string>>;
  itemBranch: string;
  catalogScopeLabel: string;
  categories: ItemCategory[];
  loadingCategories: boolean;
  loadingItems: boolean;
  filteredItems: Item[];
  catalogItems: Item[];
  customers: Customer[];
  loadingCustomers: boolean;
  applicableOffers: SalesPosApplicableOffer[];
  allowPriceSwitch: boolean;
  allowWholesalePrice: boolean;
  allowEditSellingPrice: boolean;
  salesPriceMode: PosSalesPriceMode;
  showBothPricesOnCards: boolean;
  showOffers: boolean;
  allowDeliveryCharge: boolean;
  visibleSubCategories: { id: number; name: string }[];
  activeCategoryName: string;
  categoryTabLabel: string;
  parsedCatalogSearch: { term: string; qty: number | null };
  productOfferMap: ReturnType<
    typeof import("./posProductOffers").productOffersByItemNumber
  >;
  linesSubTotal: number;
  netAmount: number;
  changeDue: number;
  vatBreakdown: ReturnType<typeof import("./posSaleTax").calculateSaleVat>;
  saleBusy: boolean;
  offerNeedsPromo: boolean;
  itemImageByNumber: Map<string, string>;
  lineImageUrl: (itemNumber?: string | null) => string | null;
  lineUom: (line: SaleLineDraft) => string;
  handleSalesPriceModeChange: (mode: PosSalesPriceMode) => void;
  handleCategoryTabChange: (tab: PosCategoryTab) => void;
  setSubCategoryTab: Dispatch<SetStateAction<PosSubCategoryTab>>;
  addItemToCart: (displayItem: Item, addQty?: number) => void;
  addMainItemToCart: (displayItem: Item, addQty?: number) => void;
  openBatchPicker: (displayItem: Item, addQty?: number) => void;
  removeFromCart: (displayItem: Item) => void;
  cartQtyForItem: (itemId: number) => number;
  handleCatalogSearchSubmit: () => void;
  setLineQty: (key: string, rawQty: number) => void;
  setLineUnitPrice: (key: string, rawPrice: number) => void;
  updateLineQty: (key: string, delta: number) => void;
  handlePaymentSelect: (method: PosPaymentMethod) => void;
  handleComplete: () => void;
  handleHold: () => void;
  resetPosForNewSale: () => void;
  resumeHoldOrder: (sale: Sale) => void;
  savePosSelectedCustomer: (customer: Customer | null) => void;
  customerDisplayName: (customer: Customer) => string;
  goToCheckout: () => void;
}
